###############################################################
# Dockerfile.base gets cached on Docker Hub.
# This way dependencies don't need to be rebuilt every CI run.
###############################################################

FROM ubuntu:resolute

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata && apt-get upgrade -y --fix-missing
RUN apt-get install -y git curl tar python3 unzip xz-utils bzip2 lbzip2 patch binutils cmake make gcovr gpg gcc g++ gfortran m4
RUN git clone https://github.com/spack/spack.git && cd spack && git checkout tags/releases/latest -b latest && cd .. && \
  . spack/share/spack/setup-env.sh && \
  spack compiler find && spack external find binutils cmake coreutils curl diffutils findutils git gmake openssh perl python sed tar m4
RUN . spack/share/spack/setup-env.sh && \
  spack env create build-env && spack env activate build-env && \
  spack add eigen@3.4.1 catch2@2.13.10 intel-oneapi-tbb parmetis kokkos+openmp+serial trilinos cxxstd=17 +openmp +amesos2 +belos +tpetra +ifpack2 +muelu
RUN . spack/share/spack/setup-env.sh && spack env activate build-env && spack concretize && \
  spack install && spack env deactivate && spack gc -y && spack clean -a
