#ifndef L3STER_UTIL_INCLUDEEIGEN_HPP
#define L3STER_UTIL_INCLUDEEIGEN_HPP

#define EIGEN_DONT_PARALLELIZE
#define EIGEN_STACK_ALLOCATION_LIMIT 0
#include "Eigen/Dense"

#endif // L3STER_UTIL_INCLUDEEIGEN_HPP
