name: CI
on: push

jobs:
        build:
                name: Catch2-Tests

                runs-on: ubuntu-latest

                steps:
                        - uses: actions/checkout@v2
                          with:
                                  submodules: true

                        - name: Configure & build
                          run: mkdir ../build
                          run: cd ../build
                          run: cmake $GITHUB_WORKSPACE/tests/
                          run: make -j4

                        - name: Run tests
                          run: $GITHUB_WORKSPACE/../build/test
