name: CI
on: push

jobs:
        build:
                name: Catch2-Tests

                runs-on: ubuntu-latest

                steps:
                        - uses: actions/checkout@v2
                          with:
                                  submodules: true

                        - name: pwd
                          run: pwd

                        - name: echo-workdir
                          run: echo $GITHUB_WORKSPACE

                        - name: ll
                          run: ls -al

                        - name: configure
                          run: mkdir build; cd build; cmake $GITHUB_WORKSPACE/L3STER/tests/

                        - name: build
                          run: make -j4

                        - name: test
                          run: ./test
