name: tests
on: [ push, pull_request ]

env:
  DOCKER_BASE: "${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_IMAGE }}:latest"
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1

jobs:
  build_base_container:
    name: Build base container
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: whoan/docker-build-with-cache-action@v5
        id: docker-base-cache
        with:
          username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          password: "${{ secrets.DOCKER_HUB_TOKEN }}"
          image_name: "${{ secrets.DOCKER_HUB_IMAGE }}"
          dockerfile: scripts/ci/Dockerfile.base

  unit_tests_and_static_analysis:
    name: Static analysis and unit tests
    needs: build_base_container
    runs-on: self-hosted
    env:
      CMAKE_BUILD_TYPE: Release
      CMAKE_TOOLCHAIN_PATH: ../cmake/toolchains/StaticAnalysis.cmake
    steps:
      - uses: actions/checkout@v3
      - name: Append docker base
        run: sed -i '1 i\FROM '"$DOCKER_BASE" $GITHUB_WORKSPACE/Dockerfile
      - uses: ./scripts/ci/run-tests

  sanitizers:
    name: Sanitizers
    needs: unit_tests_and_static_analysis
    continue-on-error: true
    runs-on: self-hosted
    env:
      CMAKE_BUILD_TYPE: ${{ matrix.build_type }}
      CMAKE_TOOLCHAIN_PATH: "../cmake/toolchains/${{ matrix.sanitizer }}Sanitizer.cmake"
    strategy:
      matrix:
        build_type: [ Debug, Release ]
        sanitizer: [ Address, Thread, UndefinedBehavior ]
    steps:
      - uses: actions/checkout@v3
      - name: Append docker base
        run: sed -i '1 i\FROM '"$DOCKER_BASE" $GITHUB_WORKSPACE/Dockerfile
      - uses: ./scripts/ci/run-tests

  coverage:
    name: Code coverage
    needs: sanitizers
    runs-on: self-hosted
    env:
      CMAKE_BUILD_TYPE: Debug
      CMAKE_TOOLCHAIN_PATH: ../cmake/toolchains/Coverage.cmake
      REPORT_COVERAGE: ON
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Append docker base
        run: sed -i '1 i\FROM '"$DOCKER_BASE" $GITHUB_WORKSPACE/Dockerfile
      - uses: ./scripts/ci/run-tests

  deployment:
    name: Deployment tests
    needs: unit_tests_and_static_analysis
    runs-on: self-hosted
    env:
      DEPLOYMENT_TESTS: true
    steps:
      - uses: actions/checkout@v3
      - name: Append docker base
        run: sed -i '1 i\FROM '"$DOCKER_BASE" $GITHUB_WORKSPACE/Dockerfile
      - uses: ./scripts/ci/run-tests
