name: Tests 
'on': push
jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure & build
        run: |
          mkdir ../build
          cd ../build
          cmake $GITHUB_WORKSPACE/tests/ \
          -D CMAKE_C_COMPILER=gcc-9 \
          -D CMAKE_CXX_COMPILER=g++-9
          make -j4
          cp $GITHUB_WORKSPACE/tests/data/. ./ -r

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE/../build/
          ls -al
          ./test -s -d yes
